-- SmartTrap dashboard: planned trap layouts (the Layout pane)
--
-- The Layout pane generates an even grid of trap positions inside the orchard
-- boundary, so a 20+ node block goes in uniformly instead of by eye. This table
-- is where that plan lives, so a layout worked out on a desktop is on the phone
-- when you walk the block.
--
-- One row per saved layout, owned by the login that made it. The pane reads and
-- writes a single row per account (order by id, limit 1), the same way
-- orchard-setup.html treats orchard_boundaries, but the table can hold more.
--
--   params  {"targetCount":20,"spacingM":91.2,"rowBearingDeg":90,
--            "setbackM":10,"stagger":true,"mode":"count"}
--   points  [{"n":1,"label":"P01","lat":37.3566,"lng":-120.9393,"role":"node"}, ...]
--
-- `role` is "node" or "repeater", the words the firmware uses in
-- SmartTrapLink.h. Nothing here enforces it, and node_locations still has no
-- role column: a PLANNED point is not a trap. A trap exists only once someone
-- stands at it and saves it from scan.html, which is what keeps the recorded
-- position the real one rather than the intended one.
--
-- Note: unlike the four original tables, this one's DDL is in source control.
-- The others were created in the Supabase UI and have no CREATE TABLE anywhere.
--
-- Run after supabase/rls-policies.sql. Paste into the SQL Editor and click Run.
-- Safe to re-run.
--
-- ⚠ If you ever add 'trap_layouts' to the table list in rls-policies.sql's
--   "drop every existing policy" loop, add its policies there too. That loop
--   drops policies for the tables it names; a table left in the list with no
--   policies re-created has RLS on and nothing allowed, so it goes silently
--   invisible to every account.

create table if not exists public.trap_layouts (
  id         bigint generated by default as identity primary key,
  name       text        not null default 'Layout 1',
  params     jsonb       not null default '{}'::jsonb,
  points     jsonb       not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  owner_id   uuid        not null default auth.uid()
                         references auth.users (id) on delete cascade
);

create index if not exists trap_layouts_owner_id_idx on public.trap_layouts (owner_id, id);

-- ── Access: signed-in users, their own rows only ────────────
alter table public.trap_layouts enable row level security;

-- Policies are OR'd, so clear any leftovers before re-creating them.
do $$
declare p record;
begin
  for p in select policyname from pg_policies
           where schemaname = 'public' and tablename = 'trap_layouts'
  loop
    execute format('drop policy %I on public.trap_layouts', p.policyname);
  end loop;
end $$;

create policy "Own layouts: read" on public.trap_layouts
  for select to authenticated using (owner_id = (select auth.uid()));
create policy "Own layouts: add" on public.trap_layouts
  for insert to authenticated with check (owner_id = (select auth.uid()));
create policy "Own layouts: edit" on public.trap_layouts
  for update to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "Own layouts: remove" on public.trap_layouts
  for delete to authenticated using (owner_id = (select auth.uid()));

-- ── Result: which login has a saved layout ──────────────────
select u.email,
       (select count(*) from public.trap_layouts l where l.owner_id = u.id) as layouts
from auth.users u
order by u.email;
